# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKb5y242gGFb_GLPeML1G7hMa5iYKOQk
"""

import requests
import smtplib
from email.mime.text import MIMEText
from datetime import datetime
def send_email(subject, body, from_email, to_email, password,
               smtp_server='smtp.gmail.com', smtp_port=587):
    msg = MIMEText(body)
    msg['Subject'] = subject
    msg['From'] = from_email
    msg['To'] = to_email

    try:
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(from_email, password)
        server.sendmail(from_email, to_email, msg.as_string())
        server.quit()
        print("Email sent successfully!")
    except Exception as e:
        print(f"Failed to send email: {e}")

def umbrella_reminder():
    city = "Hyderabad"
    api_key = "def2b9801f104aa1a8353308250910"
    url = f"http://api.weatherapi.com/v1/forecast.json?key={api_key}&q={city}&days=3"

    try:
        response = requests.get(url)
        data = response.json()

        if 'error' in data:
            print("API error:", data['error'].get('message', 'Unknown error'))
            return

        current = data['current']
        forecast = data['forecast']['forecastday']

        condition = current['condition']['text']
        temp_c = current['temp_c']
        humidity = current['humidity']
        wind_kph = current['wind_kph']
        uv_index = current['uv']
        feels_like = current['feelslike_c']

        sunrise = forecast[0]['astro']['sunrise']
        sunset = forecast[0]['astro']['sunset']


        print(f"\nCurrent weather in {city}:")
        print(f"Condition: {condition}")
        print(f"Temperature: {temp_c}°C (Feels like {feels_like}°C)")
        print(f"Humidity: {humidity}%")
        print(f"Wind: {wind_kph} km/h")
        print(f"UV Index: {uv_index}")
        print(f"Sunrise: {sunrise}, Sunset: {sunset}")


        umbrella_conditions = ['rain', 'drizzle', 'thunder', 'snow', 'shower']

        need_umbrella = any(cond.lower() in condition.lower() for cond in umbrella_conditions)


        temp_alert = ""
        if temp_c > 35:
            temp_alert = "🔥 Heat Alert: Stay hydrated!"
        elif temp_c < 15:
            temp_alert = "❄️ Cold Weather Alert: Wear warm clothes!"
        forecast_text = "\n📅 3-Day Forecast:\n"
        for day in forecast:
            date = day['date']
            cond = day['day']['condition']['text']
            avg_temp = day['day']['avgtemp_c']
            rain_chance = day['day']['daily_chance_of_rain']

            forecast_text += (
                f"\n- {date}\n"
                f"   Condition: {cond}\n"
                f"   Avg Temp: {avg_temp}°C\n"
                f"   Rain Chance: {rain_chance}%\n"
            )

        # Email body
        if need_umbrella:
            subject = "☔ Umbrella Reminder + Full Weather Report"
            body = (
                f"Hi!\n\n"
                f"Don't forget your umbrella today.\n"
                f"Current Weather in {city}:\n"
                f"• {condition}\n"
                f"• Temperature: {temp_c}°C (Feels like {feels_like}°C)\n"
                f"• Humidity: {humidity}%\n"
                f"• Wind: {wind_kph} km/h\n"
                f"• UV Index: {uv_index}\n"
                f"• Sunrise: {sunrise}\n"
                f"• Sunset: {sunset}\n\n"
                f"{temp_alert}\n"
                + forecast_text +
                "\nStay safe and dry!"
            )
        else:
            subject = "🌤 Weather Update (No Umbrella Needed)"
            body = (
                f"Hi!\n\n"
                f"No umbrella needed today.\n"
                f"Current Weather in {city}:\n"
                f"• {condition}\n"
                f"• Temperature: {temp_c}°C\n"
                f"• Humidity: {humidity}%\n"
                f"• Wind: {wind_kph} km/h\n"
                f"• UV Index: {uv_index}\n"
                f"• Sunrise: {sunrise}\n"
                f"• Sunset: {sunset}\n\n"
                f"{temp_alert}\n"
                + forecast_text +
                "\nHave a great day!"
            )

        from_email = "prasannadara17@gmail.com"
        to_email = "rushikesh1764355@gmail.com"
        email_password = "npzb cqst kiqz mfue"


        send_email(subject, body, from_email, to_email, email_password)
        with open("weather_logs.txt", "a") as log:
            log.write(f"{datetime.now()} - Weather checked: {condition}, {temp_c}°C, Umbrella: {need_umbrella}\n")

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    umbrella_reminder()





